version: '3.8'

services:
  # The React Frontend Service
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: coreforge-frontend
    networks:
      - coreforge-net
    # Wait for the backend to be healthy before starting
    depends_on:
      backend-agent:
        condition: service_healthy

  # The Python Backend Agent Service
  backend-agent:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    container_name: coreforge-agent
    networks:
      - coreforge-net
    healthcheck:
      # Test to check if the backend API is responding
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  coreforge-net:
    driver: bridge
